services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=insect_life
      - DB_USER=root
      - DB_PASS=root
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insect_life
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: